import {MessageType} from "../enum/message.enum";

export type RuleTypes = { [key: string]: MessageType }
export type ConfigModules = {
    [key: string]: RuleTypes
};
export type IConfig = {
    modules: ConfigModules
}
const config: IConfig = {
    modules: {
        seo: {
            "canonical-not-localhost": MessageType.error,
            "canonical": MessageType.error,
            "meta-description": MessageType.error,
            "empty-title": MessageType.error,
            "header-not-empty": MessageType.error,
            "header-only-one": MessageType.error,
            "header-present": MessageType.error,
            "heading-level": MessageType.error,
            "hreflang": MessageType.error,
            "image-alt": MessageType.error,
            "is-crawlable": MessageType.error,
            "link-text": MessageType.warning,
            "meta-og-present": MessageType.error,
            "structured-data-present": MessageType.warning,
            "structured-data-valid": MessageType.warning,
            "document-title-length": MessageType.error,
            "document-title": MessageType.error,
            "meta-twitter-rule": MessageType.warning
        },
        html: {
            "attr-delimiter": MessageType.warning,
            "attr-spacing": MessageType.error,
            "close-attr": MessageType.error,
            "close-order": MessageType.error,
            "element-name": MessageType.error,
            "form-dup-name": MessageType.error,
            "map-dup-name": MessageType.error,
            "map-id-name": MessageType.error,
            "no-dup-attr": MessageType.error,
            "no-dup-class": MessageType.error,
            "no-raw-characters": MessageType.error,
            "no-redundant-for": MessageType.error,
            "script-type": MessageType.error,
            "unrecognized-char-ref": MessageType.error,
            "valid-autocomplete": MessageType.error,
            "valid-id": MessageType.error,
            "attribute-allowed-values": MessageType.error,
            "attribute-misuse": MessageType.error,
            "element-permitted-content": MessageType.error,
            "element-permitted-occurrences": MessageType.error,
            "element-permitted-order": MessageType.error,
            "element-permitted-parent": MessageType.error,
            "element-required-ancestor": MessageType.error,
            "element-required-attributes": MessageType.error,
            "element-required-content": MessageType.error,
            "input-attributes": MessageType.error,
            "no-multiple-main": MessageType.error,
            "script-element": MessageType.error,
            "void-content": MessageType.error,
            "deprecated": MessageType.error,
            "deprecated-rule": MessageType.error,
            "no-conditional-comment": MessageType.error,
            "no-deprecated-attr": MessageType.error,
            "area-alt": MessageType.error,
            "aria-hidden-body": MessageType.error,
            "aria-label-misuse": MessageType.error,
            "empty-heading": MessageType.error,
            "hidden-focusable": MessageType.error,
            "input-missing-label": MessageType.warning,
            "meta-refresh": MessageType.error,
            "multiple-labeled-controls": MessageType.error,
            "no-abstract-role": MessageType.error,
            "no-autoplay": MessageType.error,
            "no-implicit-button-type": MessageType.error,
            "no-redundant-aria-label": MessageType.error,
            "no-redundant-role": MessageType.error,
            "prefer-native-element": MessageType.error,
            "svg-focusable": MessageType.warning,
            "tel-non-breaking": MessageType.error,
            "text-content": MessageType.error,
            "unique-landmark": MessageType.error,
            "wcag-h30": MessageType.error,
            "wcag-h32": MessageType.error,
            "wcag-h36": MessageType.error,
            "wcag-h37": MessageType.error,
            "wcag-h63": MessageType.error,
            "wcag-h67": MessageType.error,
            "wcag-h71": MessageType.error,
            "attr-case": MessageType.error,
            "attr-pattern": MessageType.warning,
            "class-pattern": MessageType.warning,
            "id-pattern": MessageType.warning,
            "attr-quotes": MessageType.error,
            "no-style-tag": MessageType.warning,
            "attribute-boolean-style": MessageType.error,
            "attribute-empty-style": MessageType.error,
            "doctype-style": MessageType.error,
            "element-case": MessageType.error,
            "name-pattern": MessageType.warning,
            "no-implicit-close": MessageType.error,
            "no-implicit-input-type": MessageType.error,
            "no-self-closing": MessageType.error,
            "no-trailing-whitespace": MessageType.error,
            "prefer-button": MessageType.error,
            "prefer-tbody": MessageType.error,
            "void-style": MessageType.error,
            "allowed-links": MessageType.warning,
            "doctype-html": MessageType.error,
            "missing-doctype": MessageType.error,
            "no-dup-id": MessageType.error,
            "no-missing-references": MessageType.warning,
            "no-utf8-bom": MessageType.error,
            "no-unknown-elements": MessageType.warning,
            "no-unused-disable": MessageType.warning,
        },
        security: {
            "require-csp-nonce": MessageType.warning,
            "require-sri": MessageType.warning,
            "detect-bidi-characters": MessageType.warning,
            "detect-buffer-noassert": MessageType.warning,
            "detect-child-process": MessageType.warning,
            "detect-disable-mustache-escape": MessageType.warning,
            "detect-eval-with-expression": MessageType.warning,
            "detect-new-buffer": MessageType.warning,
            "detect-no-csrf-before-method-override": MessageType.warning,
            "detect-non-literal-fs-filename": MessageType.warning,
            "detect-non-literal-regexp": MessageType.warning,
            "detect-non-literal-require": MessageType.warning,
            "detect-object-injection": MessageType.warning,
            "detect-possible-timing-attacks": MessageType.warning,
            "detect-pseudoRandomBytes": MessageType.warning,
            "detect-unsafe-regex": MessageType.warning
        }
    }
};

export { config };